# Generated by Django 4.0.4 on 2023-10-06 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("IN_PROCESS", "In Process"), ("PAID", "Paid")],
                        max_length=63,
                    ),
                ),
                ("session_url", models.URLField(blank=True, max_length=250, null=True)),
                ("session_id", models.CharField(blank=True, max_length=10, null=True)),
                ("payment_amount", models.IntegerField(default=0)),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="borrowing.borrowing",
                    ),
                ),
            ],
        ),
    ]
