# Generated by Django 4.0.4 on 2023-10-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0004_alter_borrowing_actual_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="penalty_for_delay",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
