# Generated by Django 4.0.4 on 2023-10-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0005_alter_borrowing_penalty_for_delay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="penalty_for_delay",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
